2025-07-09 15:48:55,289 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:48:55,294 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:48:55,298 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:48:55,301 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:48:55,304 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:48:55,308 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:48:55,312 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:48:55,315 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:49:00,322 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:49:00,326 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:49:00,331 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:49:00,335 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:49:00,339 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:49:00,343 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:49:00,347 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:49:00,351 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:49:00,355 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:49:05,361 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:49:05,366 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:49:05,369 [WARNING] common.clients.api: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8001: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-07-09T15:49:05.367515+02:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8001: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-07-09 15:49:05,369 [WARNING] common.clients.api: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8001: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-07-09T15:49:05.368477+02:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8001: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-07-09 15:49:05,370 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:49:05,372 [WARNING] common.clients.api: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8001: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-07-09T15:49:05.372667+02:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8001: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-07-09 15:49:05,374 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:49:05,376 [WARNING] common.clients.api: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8001: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8001: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-07-09T15:49:05.376656+02:00"}"
>
2025-07-09 15:49:05,378 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:49:05,380 [WARNING] common.clients.api: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8001: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-07-09T15:49:05.380438+02:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8001: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-07-09 15:49:05,381 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:49:05,384 [WARNING] common.clients.api: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8001: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-07-09T15:49:05.384198+02:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8001: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-07-09 15:49:05,385 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:49:05,388 [WARNING] common.clients.api: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8001: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8001: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-07-09T15:49:05.387914+02:00"}"
>
2025-07-09 15:49:05,389 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 15:49:05,391 [WARNING] common.clients.api: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8001: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-07-09T15:49:05.391702+02:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8001: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-07-09 15:49:06,841 [INFO] __main__: Shutting down gracefully...
2025-07-09 15:49:08,393 [WARNING] common.clients.api: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8001: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-07-09T15:49:08.393369+02:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8001: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-07-09 15:49:15,529 [DEBUG] asyncio: Using selector: KqueueSelector
2025-07-09 15:49:15,529 [DEBUG] grpc._cython.cygrpc: Using AsyncIOEngine.POLLER as I/O engine
2025-07-09 15:59:18,472 [DEBUG] asyncio: Using selector: KqueueSelector
2025-07-09 15:59:18,472 [INFO] __main__: Initting and starting up API RPC Service
2025-07-09 16:00:11,542 [DEBUG] asyncio: Using selector: KqueueSelector
2025-07-09 16:00:11,542 [INFO] __main__: Initting and starting up API RPC Service
2025-07-09 16:00:11,542 [DEBUG] grpc._cython.cygrpc: Using AsyncIOEngine.POLLER as I/O engine
2025-07-09 16:00:11,544 [INFO] __main__: Starting rpc service on address: 127.0.0.1:8013
2025-07-09 16:00:11,547 [ERROR] asyncio: Task exception was never retrieved
future: <Task finished name='Task-2' coro=<NannyService.monitor_loop() done, defined at /Users/test/Workspace/xisa/services/nanny/src/nanny/main.py:95> exception=AttributeError("'NannyService' object has no attribute 'api'")>
Traceback (most recent call last):
  File "/Users/test/Workspace/xisa/services/nanny/src/nanny/main.py", line 96, in monitor_loop
    await self.api.startup()
          ^^^^^^^^
AttributeError: 'NannyService' object has no attribute 'api'
2025-07-09 16:00:11,547 [INFO] __main__: Server started: 127.0.0.1:8013
2025-07-09 16:00:13,477 [INFO] __main__: Shutting down gracefully...
2025-07-09 16:00:13,495 [INFO] __main__: Server shut down.
2025-07-09 16:00:13,495 [DEBUG] __main__: Server stopped: 127.0.0.1:8013
2025-07-09 16:00:31,618 [DEBUG] asyncio: Using selector: KqueueSelector
2025-07-09 16:00:31,618 [INFO] __main__: Initting and starting up API RPC Service
2025-07-09 16:00:31,619 [DEBUG] grpc._cython.cygrpc: Using AsyncIOEngine.POLLER as I/O engine
2025-07-09 16:00:31,620 [INFO] __main__: Starting rpc service on address: 127.0.0.1:8013
2025-07-09 16:00:31,623 [INFO] __main__: Server started: 127.0.0.1:8013
2025-07-09 16:00:31,625 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 16:00:31,630 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 16:00:31,635 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 16:00:31,639 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 16:00:31,643 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 16:00:31,648 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 16:00:31,652 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 16:00:31,656 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 16:00:39,665 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 16:00:39,670 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 16:00:39,675 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 16:00:39,679 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 16:00:39,683 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 16:00:39,688 [DEBUG] common.service: Connected to grpc server securely!
2025-07-09 16:00:39,692 [DEBUG] common.service: Connected to grpc server securely!
